# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lune < Formula
  desc "Lune CLI"
  homepage "https://github.com/gentij/lune"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gentij/lune/releases/download/v1.0.0/lune_darwin_amd64.tar.gz"
      sha256 "b79d0144e295c3e7876d395c8c69d254a2d7e5af6aa4fa0a1c95ee0dc6a52b2c"

      define_method(:install) do
        bin.install "lune"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gentij/lune/releases/download/v1.0.0/lune_darwin_arm64.tar.gz"
      sha256 "584453d1b376e3b7b61b37bcfa1e9bba15919705cf6d74f6ab699b6bbed2da4b"

      define_method(:install) do
        bin.install "lune"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gentij/lune/releases/download/v1.0.0/lune_linux_amd64.tar.gz"
      sha256 "d3b06eb2e3944b85e520098bb37ee9adf5727da6a2f8c00238671344356c4eef"
      define_method(:install) do
        bin.install "lune"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gentij/lune/releases/download/v1.0.0/lune_linux_arm64.tar.gz"
      sha256 "5b09cb96dc4199416aae4831c952f2ef40ed73fe1eb9b2462da675e29f184e98"
      define_method(:install) do
        bin.install "lune"
      end
    end
  end
end
