# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lune < Formula
  desc "Lune CLI"
  homepage "https://github.com/gentij/lune"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gentij/lune/releases/download/v1.0.0/lune_darwin_amd64.tar.gz"
      sha256 "32c1b6371abba61870468fa22efa39c1846a8981a08d1cd0197beddac650265b"

      define_method(:install) do
        bin.install "lune"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gentij/lune/releases/download/v1.0.0/lune_darwin_arm64.tar.gz"
      sha256 "79a5f4cefd5d1f23dfc5c5d8abb7a7ed493e826a8b698441b651431cf94e3bc2"

      define_method(:install) do
        bin.install "lune"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gentij/lune/releases/download/v1.0.0/lune_linux_amd64.tar.gz"
      sha256 "6af5835b463052687a56b9339f626b1e6865689c99b9d5dc74333c3c0e1b90d9"
      define_method(:install) do
        bin.install "lune"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gentij/lune/releases/download/v1.0.0/lune_linux_arm64.tar.gz"
      sha256 "ab261a300ac1c4e5e39afc3bc6b27f10bce381d557c1935cfb7048c04c53ddcf"
      define_method(:install) do
        bin.install "lune"
      end
    end
  end
end
